### PR TITLE
Ft careers what we do pages shec61 shec59

### PR DESCRIPTION
**Pull request by k3lly003**
### What does this PR do?
This PR implements the careers & what we do pages.
### Description of Task to be completed?
- finalizing responsiveness
### How should this be manually tested?
This PR should be tested by switching to this branch and navigating to these pages (**careers**, **what we do**)
### What are the relevant pivotal tracker/Trello stories?
The relevant pivot Jira stories are:
- [SHEC - 59](https://igirerwanda.atlassian.net/jira/software/c/projects/SHEC/list?selectedIssue=SHEC-59)
- [SHEC - 61](https://igirerwanda.atlassian.net/jira/software/c/projects/SHEC/list?selectedIssue=SHEC-61)

### CODE REVIEW

**Comment by ishimwepacifique0** [comment]
Hello @k3lly003  Ensuring consistent spacing and layout can indeed improve the overall look and feel of a website

**Comment by k3lly003** [comment]
> Hello @k3lly003 Ensuring consistent spacing and layout can indeed improve the overall look and feel of a website

Yes

**Comment by ishimwepacifique0** [comment]
can you check again on figma follow spacing  between the  section

**Comment by k3lly003** [comment]
> can you check again on figma follow spacing between the section

yp

**Pull request closed without merging**
